### ISSUE TITLE
Only staff can upload images

### ISSUE THREAD

**Issue by shantanavKapse** [hvlads/django-ckeditor-5#115]
Hi!

I am using the django-ckeditor-5 library for implementing ckeditor 5 as blog editor, but I came across the upload file view while facing errors when uploading images. It seems that currently only staff can upload images. I think it can be an extra argument to restrict it to staff or not.

Thanks!

**Comment by hvlads** [comment]
Hello, in the file urls.py instead of

path("ckeditor5/", include("django_ckeditor_5.urls")),
you can add
path("image_upload/", [your_function](https://github.com/hvlads/django-ckeditor-5/blob/b436458b39ba4bf050d719c1bfb49336be2c40d9/django_ckeditor_5/views.py#L43), name="ck_editor_5_upload_file"),

for example:

```
def your_function(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        try:
            image_verify(request.FILES["upload"])
        except NoImageException as ex:
            return JsonResponse({"error": {"message": f"{str(ex)}"}})
        if form.is_valid():
            url = handle_uploaded_file(request.FILES["upload"])
            return JsonResponse({"url": url})
    raise Http404(_("Page not found."))

```
