### ISSUE TITLE
Add anchor plugin

### ISSUE THREAD

**Issue by ybalashkevych** [hvlads/django-ckeditor-5#147]
Hi, I was trying to add ckeditor-anchor plugin, I did but then editor stopped acception any input from keyboard however anchor worked. I forked https://github.com/bvedad/ckeditor5-anchor and updated dependencies to 38.0.1 versions to match ckeditor.

Webbrowser console says isInput is undefined and throws error. I'm not an expert in js so it's hard for me to figure out the reason.

<img width="1728" alt="Screenshot 2023-07-04 at 9 28 25 PM" src="https://github.com/hvlads/django-ckeditor-5/assets/10913696/91adf157-fbd0-43e5-bf1d-3f66c4d59106">

**Comment by hvlads** [comment]
I apologize for the inconvenience you're experiencing with the CKEditor Anchor plugin. As you correctly pointed out, since you have forked and modified the plugin to update the dependencies to match CKEditor 38.0.1, it would be best to reach out to the plugin developer for assistance.

The error you mentioned, with the `isInput` variable being undefined, indicates that there might be compatibility issues between the modified plugin and the CKEditor version you are using. The plugin may require further adjustments or updates to work correctly with the latest CKEditor version.

I recommend contacting the plugin developer directly through the repository you forked or by raising an issue on the plugin's official repository (if available). The developer will have a better understanding of the plugin's internals and can provide guidance on resolving the compatibility issue or suggest alternative solutions.

It's always advisable to work with the latest versions of plugins and their dependencies to ensure compatibility and leverage any bug fixes or improvements. The plugin developer will be able to provide you with the most accurate guidance in this case.

If you require further assistance or have any additional questions, please feel free to ask.
