### ISSUE TITLE
problem with loading ckeditor widget in template

### ISSUE THREAD

**Issue by parsamrz** [hvlads/django-ckeditor-5#152]
Hi, I have installed the ckeditor5 package in my Django app. I have model fields like bellow

`    
description = CKEditor5Field(blank=True,null=True,config_name='extends')
`
and a model form .and my problem is when I want to render a form in a template when I call {{ form.as_p }} and {{ form.media }} it will load ckeditor completely 
but when I call {{ form.description }} with  {{ form.media }} field directly it won't work can you please help me with this?

![image](https://github.com/hvlads/django-ckeditor-5/assets/31309137/e46eaeb6-cea5-4958-8681-9420ebf32317)

**Comment by parsamrz** [comment]
in console, it gives me this error 


```

Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Sx (app.js:37:56)
    at HTMLDocument.<anonymous> (app.js:73:5)


```
![image](https://github.com/hvlads/django-ckeditor-5/assets/31309137/13f8fd98-1242-4aa1-bd47-046805b6552d)

**Comment by parsamrz** [comment]
Anyone ?

**Comment by hvlads** [comment]
Hi @parsamrz ,

I understand the issue you're facing with rendering the CKEditor5Field directly in your template. When using `{{ form.description }}`, the necessary media files for CKEditor5 might not be included in the header, resulting in it not working as expected.

To ensure that CKEditor5 functions properly when rendering the `form.description` field directly, you need to include the required media files in the template header. To do this, you can use the `{{ form.media }}` template tag.

Here's an example of how you can include the required media files in the header:

```html
<!DOCTYPE html>
<html>
<head>
    <!-- Your other head content goes here -->

    <!-- Include CKEditor5 media files -->
    {{ form.media }}
</head>
<body>
    <!-- Your body content goes here -->
    
    <!-- Render the form.description field -->
    {{ form.description }}
</body>
</html>
```

By adding `{{ form.media }}` in the header, you ensure that CKEditor5's necessary JavaScript and CSS files are loaded, which will enable the correct rendering and functionality of the `form.description` field.

If you're still facing any issues after including `{{ form.media }}` in the header, please ensure that the media files are correctly linked and accessible in your Django app. Double-check the paths and ensure there are no conflicts or missing files.

I hope this helps! If you have any further questions or encounter any other difficulties, please feel free to reach out.

Best regards,
Vladislav

**Comment by hvlads** [comment]
Hi,

I understand the issue you're facing with rendering the `{{ form.description }}` field directly in your Django template with `{{ form.media }}`.

Based on the information provided, it appears to be a bug in the code. When using `{{ form.as_p }}` along with `{{ form.media }}`, the CKEditor loads correctly. However, when using `{{ form.description }}` directly with `{{ form.media }}`, the CKEditor doesn't load as expected.

To address this bug, I will investigate the issue further and work on fixing it in the latest version of the CKEditor5 package. I'll ensure that the `{{ form.description }}` field, along with `{{ form.media }}`, works seamlessly in the template, just like when using `{{ form.as_p }}`.

Thank you for bringing this to our attention, and I apologize for any inconvenience caused by the bug. Your feedback is valuable in making improvements to the package, and I'll strive to resolve this issue promptly.

If you have any more information or specific steps that might help in debugging the issue, please feel free to share them. I'll do my best to address the problem and provide an update as soon as the bug is fixed.

Best regards,
Vladislav
