### ISSUE TITLE
textarea field on ckeditor

### ISSUE THREAD

**Issue by zoomlorde** [hvlads/django-ckeditor-5#227]
hey,
i noticed that when i try to submit the form im getting a lot of errors from chrome in console about this field:
An invalid form control with name='content' is not focusable. `<textarea name=​"content" class=​"django_ckeditor_5" required id=​"id_content" data-processed=​"1" style=​"display:​ none;​">​</textarea>​`
i tried a lot to fix it and i dont realy know what to do now
should i set this field null true or i have another choice?

**Comment by 0xarnout** [comment]
Hi,
It's hard to help without knowing how the field is implemented, but at least I can give you the html cause. It happens because the form is hidden with css using 'display: none;' and the required attribute is specified. To fix this you can either remove the style="display: none;" attribute, or remove the required attribute which you can do with specifying 'blank=True' on the field. Another solution would be to add the 'novalidate' attribute, but this isn't the best solution. Source: https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable#answer-23215333.

**Comment by zoomlorde** [comment]
Thank you for taking the time
i just set null = true on the field
